############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "About"
pageRef = "/about"
weight = 2

[[main]]
name = "Blog"
pageRef = "/blog"
weight =  3

[[main]]
name = "Contact"
pageRef = "/contact"
weight = 4

[[main]]
name = "Resume"
pageRef = "/resume"
weight = 5

# footer menu
[[footer]]
name = "Home"
pageRef = "/"
weight = 1

[[footer]]
name = "About"
pageRef = "/about"
weight = 2

[[footer]]
name = "Blog"
pageRef = "/blog"
weight = 3

[[footer]]
name = "Contact"
pageRef = "/contact"
weight = 4

[[footer]]
name = "Resume"
pageRef = "/resume"
weight = 5